### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by davegregg** [mirko-laruina/gnome-night-light-adjuster#1]
> `gnome-night-light-adjuster 3000`

`gnome-night-light-adjuster: error while loading shared libraries: libncursesw.so.6: cannot open shared object file: No such file or directory`

GNOME Shell 3.24.1
Wayland
Ubuntu 17.04

**Comment by mirko-laruina** [comment]
@davegregg , you're right, it requires ncurses to work. Sorry for not having said that in the README file.
